export const SCHEDULE = [
  {
    day: 0,
    hour: 8,
    subject: 'sostenibilitat',
    color: 'cl-cell-400',
  },
  {
    day: 0,
    hour: 9,
    subject: 'projecte',
    color: 'cl-cell-500',
  },
  {
    day: 0,
    hour: 10,
    subject: 'servidor',
    color: 'cl-cell-500',
  },
  {
    day: 0,
    hour: 11,
    subject: 'servidor',
    color: 'cl-cell-500',
  },
  {
    day: 0,
    hour: 12,
    subject: 'anglès',
    color: 'cl-cell-600',
  },
  {
    day: 0,
    hour: 13,
    subject: 'optatiu',
    color: 'cl-cell-700',
  },
  {
    day: 0,
    hour: 14,
    subject: 'optatiu',
    color: 'cl-cell-700',
  },
  {
    day: 1,
    hour: 9,
    subject: 'servidor',
    color: 'cl-cell-400',
  },
  {
    day: 1,
    hour: 10,
    subject: 'servidor',
    color: 'cl-cell-400',
  },
  {
    day: 1,
    hour: 11,
    subject: 'anglès',
    color: 'cl-cell-500',
  },
  {
    day: 1,
    hour: 12,
    subject: 'desplegament',
    color: 'cl-cell-600',
  },
  {
    day: 1,
    hour: 13,
    subject: 'desplegament',
    color: 'cl-cell-600',
  },
  {
    day: 2,
    hour: 9,
    subject: 'client',
    color: 'cl-cell-400',
  },
  {
    day: 2,
    hour: 10,
    subject: 'client',
    color: 'cl-cell-400',
  },
  {
    day: 2,
    hour: 11,
    subject: 'client',
    color: 'cl-cell-400',
  },
  {
    day: 2,
    hour: 12,
    subject: 'disseny',
    color: 'cl-cell-500',
  },
  {
    day: 2,
    hour: 13,
    subject: 'disseny',
    color: 'cl-cell-500',
  },
  {
    day: 3,
    hour: 8,
    subject: 'desplegament',
    color: 'cl-cell-400',
  },
  {
    day: 3,
    hour: 9,
    subject: 'desplegament',
    color: 'cl-cell-400',
  },
  {
    day: 3,
    hour: 10,
    subject: 'anglès',
    color: 'cl-cell-500',
  },
  {
    day: 3,
    hour: 11,
    subject: 'servidor',
    color: 'cl-cell-600',
  },
  {
    day: 3,
    hour: 12,
    subject: 'servidor',
    color: 'cl-cell-600',
  },
  {
    day: 3,
    hour: 13,
    subject: 'disseny',
    color: 'cl-cell-700',
  },
  {
    day: 4,
    hour: 8,
    subject: 'disseny',
    color: 'cl-cell-400',
  },
  {
    day: 4,
    hour: 9,
    subject: 'disseny',
    color: 'cl-cell-400',
  },
  {
    day: 4,
    hour: 10,
    subject: 'tutoria',
    color: 'cl-cell-500',
  },
  {
    day: 4,
    hour: 11,
    subject: 'servidor',
    color: 'cl-cell-600',
  },
  {
    day: 4,
    hour: 12,
    subject: 'client',
    color: 'cl-cell-700',
  },
  {
    day: 4,
    hour: 13,
    subject: 'client',
    color: 'cl-cell-700',
  },
];
